### PR TITLE
Adapt for Clojure 1.9.0 and fix test

### PR DESCRIPTION
**Pull request by TristeFigure**

### CODE REVIEW

**Comment by vdmit11** [comment]
@klutometis do you still have time and will to maintain the project?
If yes, then could you please merge this pull request, and perhaps push to clojars?

Because I've been playing with reader macros recently, and found your work useful.
But in the current state it is broken for Clojure v.1.9+, and it would be nice to get it working again.

**Comment by TristeFigure** [comment]
@vdmit11, you can use `[org.clojars.tristefigure/reader-macros "1.0.2.1"]`

**Comment by klutometis** [comment]
@vdmit11, @TristeFigure: thanks for the pull requests! Sorry I missed this first time around.

**Comment by TristeFigure** [comment]
@klutometis, famed for your inventions, thanks ! I think you forgot to push the project to clojars though.

To echo @vdmit11 suggestion, I'm willing to maintain this project. I've begun cleaning up the code. I haven't made a PR yet, but you can see what I have done so far (not sure I myself agree with the changes I made, this needs some more polishing):
https://github.com/klutometis/reader-macros/compare/master...TristeFigure:custom-version?expand=1

Also I've been working on two ways to properly scope reader-macros.
- 1. Copy the clojure.lang.LispReader class and modify its read-table. Add a dispatch global reader-macro to use custom reader-classes/tables.
- 2. Hack the \( reader-macro to allow calling reader-macros attached to a symbol rather than a single char. Check out http://quickdocs.org/named-read-macros/ for an actual implementation.

So you might receive more PRs in the future from me, although I'm very incertain as to when.

Cheers !

**Comment by klutometis** [comment]
Nice, @TristeFigure, you got the reference! Pushed to clojars.

I've also added you and @vdmit11 as collaborators to the repo; is that ok?

**Pull request merged**
